---
title: "Single trait genomic selection or prediction"
author: "Tesfahun A. Setotaw"
date: "2023-08-17"
output: html_document:
  keep_md: yes
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE)
opts_knit$set(root.dir = "/Users/tas286/Documents/GitHub/Genomic_selection_wheat/Genomic_prediction_services/UC_Davis_Breeding_program/") # setting the working director 

```
```{r}
# Load package necessary for the analysis 
library(BGLR)
library(sommer)
library(lme4)
library(rrBLUP)
library(reshape2)
library(dplyr)
library(tidyverse)
library(tibble)
library(ggplot2)
library(emmeans)
```

```{r dev= "png"}
# Read phenotypic and genotypic data
# Phenotypic data
setwd("/Users/tas286/Documents/GitHub/Genomic_selection_wheat/Genomic_prediction_services/UC_Davis_Breeding_program/")
dat_F = read.csv("phenotype_UCDavis_Bread_Wheat_Breeding_2020_2022_trials.csv") # read the phenotype data 
dim(dat_F)
summary(dat_F)

dat_F$Plant_height = dat_F$Plant.height...cm.CO_321.0001301
dat_F$Test_weight = dat_F$Grain.test.weight...g.l.CO_321.0001210
dat_F$Grain_Yield = dat_F$Grain.yield...kg.ha.CO_321.0001218
dat_F$Grain_Protein = dat_F$Grain.protein.content......CO_321.0001205
dat_F$TKW = dat_F$Grain.weight...1000.kernels...g.1000.grain.CO_321.0001213
dat_F$Heading_time = dat_F$Heading.time...Julian.date..JD..CO_321.0001233
which(dat_F$Test_weight <5) #
dat_F[1015,"Test_weight"] = NA
# Quality Control for the data (QC steps)
# 1. boxplot for the trials for each traits 

Traits <- c("Plant_height", "Test_weight", "Grain_Yield", "Grain_Protein", "TKW", "Heading_time")
for(Trait in Traits){
pl = ggplot(dat_F, mapping = aes(studyName, dat_F[,Trait], fill = studyName)) +
  geom_boxplot() + theme_bw() + theme(axis.text.x = element_text(angle = 90)) + ylab(Trait) + theme(legend.position = "none")
plot(pl)
ggsave(filename = paste(c(Trait,"boxplot.png"),collapse  = "_"))
}
```

```{r}
#Checking for the distribution of the NA in each trials 
summary(dat_F)
Trials = unique(dat_F$studyName)
out = vector(mode = "list", length = length(Trials))
names(out) <- Trials1
Traits =  c("Plant_height", "Test_weight", "Grain_Yield", "Grain_Protein", "TKW", "Heading_time") # the list of traits with NA values 
#Creating the list within the list to put the observations of each trait
for(i in 1:length(out)){
 lst1 =vector(mode = "list", length = length(Traits))
 names(lst1) = Traits
out[[i]] = lst1
}
##Summarize the number of the NA
for(Trial in Trials){
  for(Trait in Traits){
 dt2 =  droplevels(dat_F[dat_F$studyName == Trial,c( "germplasmName", "replicate", paste(Trait))]) # subset the germplasmName, replicate and Trait
 dcom = dcast(data = dt2, formula = germplasmName ~ replicate, fun.aggregate = mean, value.var = paste(Trait)) # place values in wide form
 out[[Trial]][[Trait]] = dcom
  }
}

# summary of the NA value in each trial
summNA =vector(mode = "list", length = length(Trials)) # list to store the data
names(summNA) <- Trials

library(plyr)
for (Trial in Trials) {
  for(Trait in Traits){
  dtt = dat_F[dat_F$studyName == Trial,]
  tt <- as.data.frame(out[[Trial]][[Trait]])
  if(length(colnames(tt)) > 2){
  pt = apply(X = tt, MARGIN = 2, FUN = is.na) # identify trials with NA
  ptt = as.data.frame(apply(pt[,-1],2,FUN = sum))

  pttb = cbind(Trial = Trial, Trait = Trait,plot_no = length(dtt$studyName), t(data.frame(ptt)))
  
  summNA[[Trial]][[Trait]] = pttb
  }
}
}
#Join the data in the list in one dataframe 

dd_join = data.frame()

for(Trial in Trials){
  for(Trait in Traits){
  dd = summNA[[Trial]][[Trait]] 
  dd = data.frame(dd)
  dd_join = bind_rows(dd_join,dd) # to combine each data frame by row,
  
  }
}

rownames(dd_join) = NULL # the summary table for the mapping of NA values across trials 


```

```{r}
################################
# Marker data preparation , Estimating relationship marker for each genotypic protocol and merge it
#################################

# Read marker data 
library(readxl)

dat_M = read_tsv("SNPs_UCDavis_2020_Allegro_protocol_dosage.tsv", col_names = T) 
head(dat_M[,1:10])

dat_M1 = read_tsv("SNPs_UCDavis_UCD_2022GBS_V2__protocol_dosage.tsv", col_names = T) 
head(dat_M1[,1:10])


id1 = which(dat_F$germplasmName %in% colnames(dat_M)) # identify the accessions with phenotype and marker data (genotyping protocol 1)
id2 = which(dat_F$germplasmName %in% colnames(dat_M1)) # identify the accessions with phenotype and marker data (genotyping protocol 2)
dat_coM = dat_F[c(id1,id2),] # the total number of genotype with phenotype and marker data 
all(unique(dat_coM$studyName) %in% unique(dat_F$studyName)) # check if all trials represented in the selected fraction with marker data
unique(dat_F$studyName) %in% unique(dat_coM$studyName)
which(unique(dat_M1$Marker %in% dat_M$Marker)) # check if the genotyping protocol1 and protocol2 have similar marker name

length(which(dat_M$Marker %in% dat_M1$Marker)) # the length of the intersection with the two protocols 
length(unique(dat_M$Marker))# the number of markers in protocol 1 
length(unique(dat_M1$Marker)) # the number of markers in protocol2

idg = which(unique(dat_F$germplasmName) %in% c(colnames(dat_M1)[-1], colnames(dat_M)[-1])) # The number of marker with phenotype and marker data 
list_geno_wo_marker = unique(dat_F$germplasmName)[-idg] # list of accessions without marker data
data.frame(list_geno_wo_marker)




# identify accession with marker data in each year 
years = c("2020", "2021", "2022")
Marker_by_year = tibble()
for(i in years){
  dat_y<- dat_F[dat_F$studyYear == i,] # sub-setting using year
  No_acc = length(unique(dat_y$germplasmName)) # the number of accessions 
  No_trial = length(unique(dat_y$studyName)) # the number of trials 
  Acc_M1 = length(which(unique(dat_y$germplasmName) %in% colnames(dat_M))) # identify accession with marker data (protocol 1)
  Acc_M2 = length(which(unique(dat_y$germplasmName) %in% colnames(dat_M1))) # identify accession with marker data (protocol 2)
  
id1 = which(unique(dat_y$germplasmName) %in% colnames(dat_M))
id2 = which(unique(dat_y$germplasmName) %in% colnames(dat_M1))
Acc_M1M2 = length(which(unique(dat_y$germplasmName)[id1] %in% unique(dat_y$germplasmName)[id2])) # accession with two genotyping protocol
acce_Mark = cbind(Year = i, No_of_accession = No_acc, No_trial = No_trial, Acc_genoProtocol1 = Acc_M1, Acc_genoProtocol2 = Acc_M2, Acc_Both_protocols = Acc_M1M2 )

Marker_by_year = rbind(Marker_by_year, acce_Mark)


}
Marker_by_year

###########################
# The accessions genotyped in each trial 
Acc_With_Mark_in_Trials = tibble()
for(Trial in Trials){
  dtr = dat_F[dat_F$studyName == Trial,]
  gemark1 =which(unique(dtr$germplasmName) %in% colnames(dat_M)[-1])
  nmark1 = length(gemark1)
  gemark2 = which(unique(dtr$germplasmName) %in% colnames(dat_M1)[-1])
  nmark2 = length(gemark2)
  intmark = length(intersect(unique(dtr$germplasmName)[gemark1],y = unique(dtr$germplasmName)[gemark2]))
  TotNoMark = nmark1 + nmark2 - intmark
  Accgen = cbind(Trial = Trial, No_Accession_protocl1 = nmark1, No_Accession_protocol2 = nmark2, No_common_Accessions = intmark, 
                 Total_Genotyped = TotNoMark, Total_accessions = length(unique(dtr$germplasmName)))
  Acc_With_Mark_in_Trials = rbind(Acc_With_Mark_in_Trials,Accgen)
}
str(Acc_With_Mark_in_Trials) # The Marker distribuition across trials 
Acc_With_Mark_in_Trials$No_Accession_protocl1 = as.numeric(Acc_With_Mark_in_Trials$No_Accession_protocl1)
Acc_With_Mark_in_Trials$No_Accession_protocol2 = as.numeric(Acc_With_Mark_in_Trials$No_Accession_protocol2)
Acc_With_Mark_in_Trials$No_common_Accessions = as.numeric(Acc_With_Mark_in_Trials$No_common_Accessions)
Acc_With_Mark_in_Trials$Total_Genotyped = as.numeric(Acc_With_Mark_in_Trials$Total_Genotyped)
Acc_With_Mark_in_Trials$Total_accessions = as.numeric(Acc_With_Mark_in_Trials$Total_accessions)

######################################
# Plotting the graph
#Change the data to long type 
Acc_With_Mark_in_Trials_long = tibble()
for(i in colnames(Acc_With_Mark_in_Trials)[-1]){
  dd = Acc_With_Mark_in_Trials[,c("Trial",i)]
  colnames(dd)[2] <- "Values"
  bb1 = cbind(dd, Genotyping_protocol = i)
  Acc_With_Mark_in_Trials_long = rbind(Acc_With_Mark_in_Trials_long, bb1)
}

str(Acc_With_Mark_in_Trials_long)
Acc_With_Mark_in_Trials_long$Trial = as.factor(Acc_With_Mark_in_Trials_long$Trial)
Acc_With_Mark_in_Trials_long$Genotyping_protocol = as.factor(Acc_With_Mark_in_Trials_long$Genotyping_protocol)

Acc_With_Mark_in_Trials_long$Genotyping_protocol <- factor(Acc_With_Mark_in_Trials_long$Genotyping_protocol, levels = c("No_Accession_protocl1",  "No_Accession_protocol2", "No_common_Accessions" , "Total_Genotyped",   "Total_accessions"))

#The plot to visualize the marker distribuition across trials 
ggplot(data = Acc_With_Mark_in_Trials_long, aes(x = Trial, y = Values, fill = Genotyping_protocol)) +
  geom_col(position = "dodge") +   
  geom_text(aes(label = Values), vjust = 1, size = 3, position = position_dodge(1)) + 
  scale_color_manual(values = c("#E7B800", "#2E9FDF", "#FC4E07", "blue", "green")) + 
   theme_bw() + theme(axis.text.x = element_text(angle = 90))

# Summarize the trait availability in each trials 
Traits_colname <- colnames(dat_F)[31:117] # the trait names
Trials <- unique(dat_F$studyName) # the trial names
Traitsum = tibble() # empty box for storing the output
for(Trial in Trials){
for(Trait in Traits){
dat1 = dat_F[dat_F$studyName %in% Trial,Trait]
cnt = length(which(!is.na(dat1)))
cnt1 = cbind(Trial = paste(Trial),Trait = paste(Trait),Not_na = cnt)
Traitsum = rbind(Traitsum, cnt1) # the frequeny o traits in each trial 
}
}
dim(Traitsum) 
library(reshape2) # loading the reshape package
Traitsum$Not_na = as.numeric(Traitsum$Not_na)
datsum = dcast(data = Traitsum, formula = Trial ~ Trait, fun.aggregate = mean, value.var = "Not_na", rm.na = T) # Trial by trait count
Trial_pheno = tibble()

  dtt = datsum[, 2:7]
  colnames(datsum)
  for(Trait in colnames(dtt)){
    cnt = length(which(dtt[,Trait]!=0))
    trcnt = cbind(Trait = Trait, Trial_count = cnt)
    Trial_pheno = rbind(Trial_pheno, trcnt)
  }

Trial_pheno # The Trait availability in the trials 
Acc_With_Mark_in_Trials # the marker distribuition across trials 
dd_join # The NA values distribuition across trials 

out_summ = list(Trait_avalibility = Trial_pheno, Marker_dist_acros_trial = Acc_With_Mark_in_Trials, Na_Values_dist_Trial = dd_join)

library(openxlsx)
write.xlsx(x = out_summ, file = "The_summary_Marker_NA_Trait_availability.xlsx", rowNames = T)
write.csv(x = datsum, file = "Trial_vs_traits_summary_UCDAVIs_BreedingProg.csv")
```




```{r}
###########################################
# Phenotypic data quality control
#Estimate individual location heritability for replicated trials 
###########################################
dat_F$studyName = as.factor(dat_F$studyName)
dat_F$replicate = as.factor(dat_F$replicate)
dat_F$germplasmName = as.factor(dat_F$germplasmName)
dat_F$studyYear = as.factor(dat_F$studyYear)
Trials <- unique(dat_F$studyName)

Traits
#Identifying trials with more than one replication - since we cant estimate H2 for the trials without replication.
Trials1 = c()
for(Trial in Trials){
  dt = droplevels(dat_F[dat_F$studyName == Trial,])
  r = length(unique(dt$replicate))

  if(r > 1){
    Trials1 = c(Trials1,Trial) # trials with more than one replication 
  }
}

#Trials with single rep trials 
Trial_unrep = unique(dat_F$studyName)[!unique(dat_F$studyName) %in% Trials1]


#####################################
# Categorize trials with spatial and without spatial 
Trial_spatial = c()
for(Trial in Trials1){
dd= dat_F[dat_F$studyName == Trial,]

ln = length(which(!is.na(dd$rowNumber)))
if(ln > 0){
  Trial_spatial = c(Trial_spatial, Trial)
}
}
Trial_spatial # Trials with spatial inforamtion 
Trials_WO_sp = Trials1[!Trials1 %in% Trial_spatial] # The trials without spatial information 



##########################
# Estimating heritability - without spatial correction for all the trials with replications >1  
#########################
H2 <- tibble()
BLUEMean = tibble() # Blue mean without spatial correction for all the trial 
Varcomp = tibble()
for(Trial in Trials1){
  dt = droplevels(dat_F[dat_F$studyName == Trial,])
  r = length(unique(dt$replicate))
  Traits1 = c()
 for(Trait in Traits){


  if(length(which(!is.na(dt[,Trait]))) > 0.5*length(dt$germplasmName)){
    Traits1 = c(Traits1, Trait)
  }
 }
 

  
for(Trait1 in Traits1){
  #remove outliers 
  #remove outliers - the outlier removed using studentizedr value >3 
      #removing outlier for replicated trials 
      eval(parse(text = paste("outl1 <- lmer(",Trait1,"~(1|germplasmName) + (1|replicate),
               data= dt)")))
  
  
      outlier = which(abs(stats::rstudent(outl1)) > 3)
      if(length(outlier) == 0){
        dt1 = dt}else{
          
          dt1 = dt[-outlier,]
        }

   eval(parse(text = paste( "av = mmer(fixed = ",Trait1," ~ 1,
              random = ~ germplasmName + replicate,
              rcov = ~units, data = dt1)")))
    ss = summary(av)
    ss1 = ss$varcomp
    rownames(ss1) <- c("germplasmName", "replicate","residual")
    vg = ss1["germplasmName", "VarComp"]
    ve = ss1["residual", "VarComp"]
    h2 = vg/(vg + (ve/r))
    hert = cbind(Trial = paste(Trial), Trait = paste(Trait1), Heritability = round(h2,3))
    H2 = rbind(H2,hert)
    vc = cbind(Trial = Trial, Trait = Trait1, vg = round(vg,3), ve = round(ve,3))
 ##Predicting the BLUE values
    eval(parse(text = paste( "av1 = mmer(fixed = ",Trait1," ~ germplasmName,
           random = ~ replicate,
           rcov = ~units, data = dt1)")))
 

 pp = predict(object = av1, D = "germplasmName")
 m1 = pp$pvals
 mean1 = cbind(Trial = Trial, Trait = Trait1, germplasmName = m1[,1], BLUE_mean = round(m1[,2],2))
 BLUEMean = rbind(BLUEMean, mean1)
 
 Varcomp = rbind(Varcomp,vc)
  }
}
unique(BLUEMean$Trait)

unique(BLUEMean$Trial)

H2
Varcomp$ve = as.numeric(Varcomp$ve)
Varcomp[order(Varcomp$Trait),]
library(reshape2)
H2$Heritability = as.numeric(H2$Heritability)
H2dec50P = dcast(data = H2, formula = Trial ~ Trait, fun.aggregate = mean, value.var = "Heritability")
write.csv(x = H2dec50P, file = "Heritability_for19Trials_50PNA.csv", row.names = F)
```


```{r}

##########################################
# Estimating the BLUE Without spatial data 
##########################################
#Data without spatial 
Trials_WO_sp # list of trials without spatial information 
data_Tr_WO_sp = droplevels(dat_F[dat_F$studyName %in% Trials_WO_sp, ])

BLUEMean_WO_SP = tibble()
Varcomp_wo_sp = tibble()
for(Trial in Trials_WO_sp){
  dt = droplevels(data_Tr_WO_sp[data_Tr_WO_sp$studyName == Trial,])
  r = length(unique(dt$replicate))
  Traits1 = c()
 for(Trait in Traits){


  if(length(which(!is.na(dt[,Trait]))) > 0.5*length(dt$germplasmName)){ # removing traits if morethan 50% of the obsrevation are Na
    Traits1 = c(Traits1, Trait)
  }
 }

for(Trait1 in Traits1){
  #remove outliers - the outlier removed using studentizedr value >3 
      #removing outlier for replicated trials 
      eval(parse(text = paste("outl1 <- lmer(",Trait1,"~(1|germplasmName) + (1|replicate),
               data= dt)")))
      
      outlier = which(abs(stats::rstudent(outl1)) > 3)
      if(length(outlier) == 0){
        dt = dt}else{
          
          dt = dt[-outlier,]
        }
    
    eval(parse(text = paste( "av1 = mmer(fixed = ",Trait1," ~ germplasmName,
           random = ~ replicate,
           rcov = ~units, data = dt)")))

#Extract the error variances
    eval(parse(text = paste( "av2 = mmer(fixed = ",Trait1," ~ 1,
           random = ~ germplasmName + replicate,
           rcov = ~units, data = dt)")))
    ss = summary(av2)
    ss1 = ss$varcomp
    rownames(ss1) <- c("germplasmName", "replicate","residual")
    vg = ss1["germplasmName", "VarComp"]
    ve = ss1["residual", "VarComp"]
    vc = cbind(Trial = Trial, Trait = Trait1, vg = round(vg,3), ve = round(ve,3))
  
    #option 1
    # fit = fitted(av1)
    # head(fit$dataWithFitted %>% group_by(germplasmName) %>%
    # summarise_at(.vars = "Xb.fitted",.funs = mean, na.rm = T))
 pp = predict(object = av1, D = "germplasmName")
 m1 = pp$pvals
 head(m1)
 mean1 = cbind(Trial = Trial, Trait = Trait1, germplasmName = m1[,1], BLUE_mean = round(m1[,2],2))
 BLUEMean_WO_SP = rbind(BLUEMean_WO_SP, mean1)
 Varcomp_wo_sp = rbind(Varcomp_wo_sp,vc)
  }
}
str(BLUEMean_WO_SP)
BLUEMean_WO_SP$BLUE_mean = as.numeric(BLUEMean_WO_SP$BLUE_mean)
Varcomp_wo_sp[order(Varcomp_wo_sp$Trait), ]
BLUEMean_WO_SP$BLUE_mean = as.numeric(BLUEMean_WO_SP$BLUE_mean)
BLUEMean_WO_SP_wide = dcast(data = BLUEMean_WO_SP, formula = Trial + germplasmName ~Trait, fun.aggregate = mean, value.var = "BLUE_mean" , na.rm = T)
summary(BLUEMean_WO_SP_wide)

ggplot(BLUEMean_WO_SP, mapping = aes(x = Trial, y = BLUE_mean )) +
  geom_boxplot()+ facet_wrap(~Trait, scales = "free") + theme(axis.text.x = element_text(angle = 90))

################################################
# BLUE mean for trials with spatial information 
#################################################
Trial_spatial #Trial list with spatial analysis 

data_Tr_With_Sp = droplevels(dat_F[dat_F$studyName %in% Trial_spatial,])
summary(data_Tr_With_Sp)
BLUEMean_With_SP = tibble()
for(Trial in Trial_spatial){
  dt = droplevels(data_Tr_With_Sp[data_Tr_With_Sp$studyName == Trial,])
  r = length(unique(dt$replicate))
  Traits1 = c()
 for(Trait in Traits){


  if(length(which(!is.na(dt[,Trait]))) > 0.5*length(dt$germplasmName)){
    Traits1 = c(Traits1, Trait)
  }
 }

for(Trait1 in Traits1){
  #remove outliers - the outlier removed using studentizedr value >3 
      #removing outlier for replicated trials 
      eval(parse(text = paste("outl1 <- lmer(",Trait1,"~(1|germplasmName) + (1|replicate),
               data= dt)")))
      
      outlier = which(abs(stats::rstudent(outl1)) > 3)
      if(length(outlier) == 0){
        dt = dt}else{
          
          dt = dt[-outlier,]
        }
    

 ##Predicting the BLUE values
    eval(parse(text = paste( "av1 = mmer(fixed = ",Trait1," ~ germplasmName,
           random = ~ replicate +  spl2Da(rowNumber,colNumber),
           rcov = ~vsr(units), data = dt)")))
#################################################
# Better method
     fit1 = fitted(av1)
     fited_mean = fit1$dataWithFitted
     head(fited_mean)
     BLUE_Adj = fited_mean %>% group_by(germplasmName) %>%
       summarise_at(.vars = "Xb.fitted", .funs = mean, na.rm = T)
     colnames(BLUE_Adj)[2] = "BLUE_mean"
     BLUE_Adj = cbind(Trial = Trial, Trait = Trait1, BLUE_Adj)
     
     # BLUE_Adj$Group = "Without_spatial"
    
    
#################################
 #  genname = gsub(pattern = "germplasmName", replacement = "", av1$Beta$Effect)[-1] # genotypes in the mean
 # 
 # ix = which(table(dt$germplasmName[which(is.na(dt[,Trait1]))])>1) # genotypes with NA values
 # genname_final = droplevels(unique(dt$germplasmName)[!unique(dt$germplasmName) %in% names(ix)]) # genotypes with the predicted mean
 # gno_int = droplevels(genname_final[!genname_final %in% genname]) # genotypes name of the intercept
 # 
 # GMean = av1$Beta[1,3] # The grande mean or the intercept
 # av1$Beta[2:length(av1$Beta[,1]),3] = av1$Beta[2:length(av1$Beta[,1]),3] + GMean # predicted mean (intercept + effects)
 # av1$Beta$Effect = as.character(av1$Beta$Effect) # change as character the effect coloumn
 # av1$Beta[1,2] = as.character(gno_int) #replace the "intercept" with genotypes names
 # av1$Beta$Effect = gsub(pattern = "germplasmName", replacement = "", x = av1$Beta$Effect) # remove the prefix germplasmName from the predicted mean
 # colnames(av1$Beta)[2] = "germplasmName" # rename the coloumn Effect with germplasmName
 # mean1 = cbind(Trial = Trial,av1$Beta) # save as mean1
 # colnames(mean1)[4] = "BLUE_mean"
 # head(mean1)
 # head(BLUE_Adj)
 BLUEMean_With_SP = rbind(BLUEMean_With_SP, BLUE_Adj) # save as a tibble 
  }
}
head(BLUEMean_With_SP)

BLUEMean_With_SP$BLUE_mean = as.numeric(BLUEMean_With_SP$BLUE_mean)
BLUEMean_With_SP_wide = dcast(data = BLUEMean_With_SP, formula = Trial + germplasmName ~ Trait, fun.aggregate = mean, 
                              value.var = "BLUE_mean", na.rm = T)
summary(BLUEMean_With_SP_wide)


ggplot(BLUE_Mean_replicated, mapping = aes(x = Trial, y = BLUE_mean)) +
  geom_boxplot() + facet_wrap(~Trait, scales = "free")
head(BLUE_Mean_replicated)
# To visiualize by subsetting trials and traits of interest
bdb = BLUE_Mean_replicated[BLUE_Mean_replicated$Trial == "UCD20016" & BLUE_Mean_replicated$Trait == "Test_weight" ,]
ggplot(dt, mapping = aes(x = germplasmName, y = Test_weight))+
  geom_boxplot() + theme_bw() + theme(axis.text.x  = element_text(angle = 90)) 


```



```{r}

#################################################
# Mean of the trials with single replication - for traits observed in one of the replication 
#################################################

#Group 1. Heading time and plant height - Group1 Trials list single rep observation for these traits
Trial_g1 = c("UCD20010", "UCD20013","UCD20014","UCD20015","UCD20016", "UCD20017","UCD21010", "UCD21011","UCD21013", "UCD21016","UCD21017")
Trait_g1 = c("Heading_time","Plant_height")
dim(dat_g1)
dat_g1 = droplevels(dat_F[dat_F$studyName %in% Trial_g1, c("studyName", "germplasmName", "replicate",Trait_g1)]) #subset trials with the above condition
BLUE_g1 = tibble() # To store the BLUE values
summary(dat_g1)
for(Trait in Trait_g1){
suMean = dat_g1 %>% group_by(studyName, germplasmName) %>%
  summarise_at(.vars = Trait,.funs = mean, na.rm = T)
  suMean$Trait = Trait
  colnames(suMean)[1:3] = c("Trial", "germplasmName", "BLUE_mean")
  suMean = suMean[,c(1,4,2,3)]
  BLUE_g1 = rbind(BLUE_g1, suMean)
}


#2. Grain protein, Testweight, TKW
Trial_g2 = c("UCD21011","UCD21016","UCD21017", "UCD22013","UCD22014","UCD22015","UCD22016","UCD22017","UCD22018","UCD22019" )
Trait_g2 = c("Grain_Protein", "Test_weight", "TKW")
dat_g2 = droplevels(dat_F[dat_F$studyName %in% Trial_g2, c("studyName", "germplasmName", "replicate",Trait_g2)])
summary(dat_g2)
BLUE_g2 = tibble()

for(Trait in Trait_g2){
suMean1 = dat_g2 %>% group_by(studyName, germplasmName) %>%
  summarise_at(.vars = Trait,.funs = mean, na.rm = T)
  suMean1$Trait = Trait
  colnames(suMean1)[1:3] = c("Trial", "germplasmName", "BLUE_mean")
  suMean1 = suMean1[,c(1,4,2,3)]
  BLUE_g2 = rbind(BLUE_g2, suMean1)
}

comb_Mean_singleRep = rbind(BLUE_g1,BLUE_g2) # The combined single rep mean of the trials 
comb_Mean_singleRep = as.data.frame(comb_Mean_singleRep)
head(comb_Mean_singleRep)
BLUEMean_WO_SP
BLUEMean_With_SP
comb_Mean_singleRep
comb_Mean_singleRep_wide = dcast(data = comb_Mean_singleRep, formula = Trial + germplasmName ~ Trait, 
                                 fun.aggregate = mean, value.var = "BLUE_mean", na.rm = T)
summary(comb_Mean_singleRep_wide)

ggplot(BLUE_mean_SingleREp_Wo, mapping = aes(x = Trial, y = BLUE_mean)) +
  geom_boxplot() + facet_wrap(~Trait, scales = "free") + theme(axis.text.x = element_text(angle = 90))
```


```{r}
################################################
# Mean value of the trials single rep for all the traits - 
##################################################
#Subset the trials satisfy the condition (single rep for all trials)
dat2tr = droplevels(dat_F[dat_F$studyName %in% c("UCD21015","UCD21014"), c("studyName", "germplasmName","replicate","Plant_height" , "Grain_Yield",   "Heading_time",  "Test_weight",   "Grain_Protein", "TKW" )])
dim(dat2tr)
unique(dat2tr$replicate) # check the number of replications 
#Summarize the mean data by trial and germplasm name 
dat2rmean = dat2tr %>% group_by(studyName, germplasmName) %>% 
  summarise_at(.vars = c("Grain_Protein","Grain_Yield", "Heading_time", "Plant_height",  "Test_weight",  "TKW"), .funs = mean, 
              na.rm = T)
head(dat2rmean)
Mean_Trial_SinRep_for_allTraits = as.data.frame(dat2rmean) # save it with new name 
head(Mean_Trial_SinRep_for_allTraits)
summary(Mean_Trial_SinRep_for_allTraits)
# Removing the outlier using boxstatistics 
for(Trial in c("UCD21014","UCD21015")){
for(Trait in Traits){
df = Mean_Trial_SinRep_for_allTraits[Mean_Trial_SinRep_for_allTraits$studyName == Trial,] 
idot = which(df[,Trait] %in% boxplot.stats(df[,Trait])$out)
if(length(idot) == 0){
  Mean_Trial_SinRep_for_allTraits[,Trait] = Mean_Trial_SinRep_for_allTraits[,Trait]
}else{
Mean_Trial_SinRep_for_allTraits[Mean_Trial_SinRep_for_allTraits$studyName == Trial,Trait][idot] = NA
}

}
}

summary(Mean_Trial_SinRep_for_allTraits)
ggplot(Mean_Trial_SinRep_for_allTraits, mapping = aes(x = studyName,y = Test_weight, fill = studyName)) + geom_boxplot()

#Visualize the data - for single rep trials 
Mean_Trial_SinRep_for_allTraits_long = tibble()
for(i in colnames(Mean_Trial_SinRep_for_allTraits)[-c(1,2)] ){
  dt = Mean_Trial_SinRep_for_allTraits[,i]
  dt1 = cbind(Mean_Trial_SinRep_for_allTraits[,1:2], Trait = i, Values = dt)
  Mean_Trial_SinRep_for_allTraits_long = rbind(Mean_Trial_SinRep_for_allTraits_long, dt1)
}

Mean_Trial_SinRep_for_allTraits_long_wide = dcast(data = Mean_Trial_SinRep_for_allTraits_long, formula = studyName + germplasmName ~ Trait, fun.aggregate = mean, value.var = "Values", na.rm = T)
summary(Mean_Trial_SinRep_for_allTraits_long_wide)
head(Mean_Trial_SinRep_for_allTraits_long)
colnames(Mean_Trial_SinRep_for_allTraits_long)[4] = "BLUE_mean"
ggplot(Mean_Trial_SinRep_for_allTraits_long, mapping = aes(x = studyName,y = Values, fill = Trait)) + geom_boxplot() +
  facet_wrap(~Trait, scales = "free")


```
```{r}
##################################################
# Combine Means of all groups of Trial together - as wide type 
###################################################
BLUEMean_WO_SP  # BLUE mean for trials without spatial
head(BLUEMean_WO_SP_wide)
head(BLUEMean_With_SP_wide)
comb_Mean_singleRep_wide
Mean_Trial_SinRep_for_allTraits_long_wide

head(BLUEMean_WO_SP)
BLUEMean_With_SP # BLUE mean for trials with spatial
head(BLUEMean_With_SP)
comb_Mean_singleRep # Mean for trials with single rep in some traits
head(comb_Mean_singleRep)
Mean_Trial_SinRep_for_allTraits_long # Mean of single rep trials for all the traits 
head(Mean_Trial_SinRep_for_allTraits_long)
colnames(Mean_Trial_SinRep_for_allTraits_long)[1] = "Trial"
colnames(Mean_Trial_SinRep_for_allTraits_long)[4] = "BLUE_mean"
Mean_Comb_All_Trials = rbind(BLUEMean_WO_SP,BLUEMean_With_SP,comb_Mean_singleRep, Mean_Trial_SinRep_for_allTraits_long) # All the blue means combined 
summary(Mean_Comb_All_Trials)
#Change the combined mean to wide type 
library(reshape2)
Mean_Comb_All_Trials$BLUE_mean = as.numeric(Mean_Comb_All_Trials$BLUE_mean)

Mean_Comb_TralsWide = dcast(data = Mean_Comb_All_Trials, formula = Trial + germplasmName ~ Trait, fun.aggregate = mean, value.var = "BLUE_mean", na.rm = T)

colnames(Mean_Comb_Trals1Wide)[1] = "studyName"
head(Mean_Comb_TralsWide)
summary(Mean_Comb_TralsWide)

ggplot(data = BLUE_Mean_Combined_All_Trails, mapping = aes(x = studyName, y = Test_weight, fill = studyName))+
  geom_boxplot() + theme_bw() + theme(axis.text.x  = element_text(angle = 90), legend.position = "none") 
```


```{r}
#####################################################
# Estimating the BLUE mean of genotypes over trials
######################################################
Mean_Comb_TralsWide # Mean of the trials 

str(Mean_Comb_TralsWide)
colnames(Mean_Comb_TralsWide)[1] = "studyName"
unique(Mean_Comb_TralsWide$studyName)
unique(Mean_Comb_TralsWide$germplasmName)

summary(Mean_Comb_TralsWide)

####################################################
# Removing outliers from BLUE mean of each trial
####################################################
BLUE_Comb_mean_Wo_outlier = tibble()
for(Trial in Trials){

  df = Mean_Comb_TralsWide[Mean_Comb_TralsWide$studyName == Trial,]
  for (Trait in Traits) {
  id_out = which(df[,paste(Trait)] %in% boxplot.stats(df[,paste(Trait)])$out)
  if(length(id_out) > 0){
    df[id_out,paste(Trait)] = NA
    
  }
   
  }
  BLUE_Comb_mean_Wo_outlier= rbind(BLUE_Comb_mean_Wo_outlier,df)
}
summary(BLUE_Comb_mean_Wo_outlier)
ggplot(BLUE_Comb_mean_Wo_outlier, mapping = aes(x = studyName, y = Grain_Protein)) +
  geom_boxplot() + theme_bw() + theme(axis.text.x = element_text(angle = 90))


#########################################################
# Estimating the BLUE mean of the genotypes over trials
##########################################################
library(LMMsolver)

BLUE_Means_Over_Trials = tibble()
for(Trait1 in Traits){
  
    
  eval(parse(text = paste( "out1 = lmer(",Trait1," ~ (1|germplasmName) + (1|studyName), 
                        data = BLUE_Comb_mean_Wo_outlier)"))) # removing outliers using the rstudentized test 
  outlier = which(abs(stats::rstudent(out1)) > 3)
      if(length(outlier) == 0){
         BLUE_Comb_mean_Wo_outlier= BLUE_Comb_mean_Wo_outlier}else{
          
          BLUE_Comb_mean_Wo_outlier = BLUE_Comb_mean_Wo_outlier[-outlier,]
        }
  
  ####
     #Estimate the BlUE mean of the genotypes
  eval(parse(text = paste(
    "LMM = LMMsolve(fixed = ",Trait1," ~ germplasmName, random = ~ studyName + studyName:germplasmName, data = BLUE_Comb_mean_Wo_outlier)")))
  
Lmm_coef = coef(LMM) 
PredMean = as.data.frame(Lmm_coef$germplasmName + Lmm_coef$`(Intercept)`) # Extract the predicted values
colnames(PredMean)[1] = "Pred_mean"
PredMean$germplasmName = gsub(pattern = "germplasmName_", replacement = "", x = rownames(PredMean))  
head(PredMean)
PredMean[,2]
PredMean = PredMean[order(PredMean[,2]),]
PredMean1 = cbind(Trait = Trait1, PredMean)
BLUE_Means_Over_Trials = rbind(BLUE_Means_Over_Trials, PredMean1)
}


unique(BLUE_Means_Over_Trials$germplasmName)
dim(BLUE_Means_Over_Trials)
head(BLUE_Means_Over_Trials)

ggplot(data = BLUE_Means_Over_Trials, mapping = aes(x = Trait, y = Pred_mean) ) +
  geom_boxplot() + facet_wrap(~Trait, scales = "free")
unique(BLUE_Means_Over_Trials$Trait)
boxplot.stats(BLUE_Means_Over_Trials[BLUE_Means_Over_Trials$Trait == "TKW","BLUE_mean"])$out
###################################
# BLUE_Means_over_Trials wide type

BLUE_Means_Over_Trials_wide = dcast(data = BLUE_Means_Over_Trials, formula = germplasmName ~ Trait, 
                                    fun.aggregate = mean, 
      value.var = "Pred_mean")

summary(BLUE_Means_Over_Trials_wide)

```

```{r}
############################
# Read marker data - organization 
###############################
library(readxl)

dat_M = read_tsv("SNPs_UCDavis_2020_Allegro_protocol_dosage.tsv", col_names = T) 
head(dat_M[,1:10])
dat_M = as.data.frame(dat_M)
rownames(dat_M) <- dat_M$Marker
dat_M = dat_M[,-1]
head(dat_M[,1:10])
dat_M1 = read_tsv("SNPs_UCDavis_UCD_2022GBS_V2__protocol_dosage.tsv", col_names = T) 
head(dat_M[,1:10])
dat_M1 = as.data.frame(dat_M1)
rownames(dat_M1) <- dat_M1$Marker
dat_M1 = dat_M1[,-1]
head(dat_M1[,1:10])

  
# Marker data imputation and estimation of relationship matrix 
#1. remove markers with NA values > 50%
#1.1 for the first genotyping protocol
  dim(dat_M)
  dat_Mt = t(dat_M)
  str(dat_Mt)
  for(i in colnames(dat_Mt)){
    if(length(which(is.na(dat_Mt[,i]))) >= round(length(rownames(dat_Mt)) *.50)){
      dat_Mt = dat_Mt[,!colnames(dat_Mt) %in% i]
    }
    
  }
#1.2. for the second genotyping protocol
 dim(dat_M1)
  dat_M1t = t(dat_M1)
  str(dat_M1t)
  for(i in colnames(dat_M1t)){
    if(length(which(is.na(dat_M1t[,i]))) >= round(length(rownames(dat_M1t)) *.50)){
      dat_M1t = dat_M1t[,!colnames(dat_M1t) %in% i]
    }
    
  }
  dim(dat_M1t)
  head(dat_M1t[, 1:20])
  
  
  #Filtering the marker data based on the MAF (minimum allel frequency)
  
  library(genomicMateSelectR)
   datMt = maf_filter(M = dat_Mt, thresh = 0.05)
   
   dim(datMt)
   dat_M1t = maf_filter(M = dat_M1t, thresh = 0.05)
   dim(dat_M1t)
  
   
# Estimate the hetrozygot proportion 
  # group 1
  
  hetr1 = tibble()
    
   for(i in colnames(datMt)){
    p = length(which(datMt[,i] == 1))/length(rownames(datMt)) # hetrozygosity estimate 
   
     hetr1 = rbind(hetr1,p)
  
    }
 
  idh = which(hetr1[,1] > 0.2)
  if(length(idh) == 0){
  datMt = datMt}else{
     datMt = datMt[, -idh]
  }
 
  dim(datMt)
  
  
  #group2
  hetr2 = tibble()
    
   for(i in colnames(dat_M1t)){
    p = length(which(dat_M1t[,i] == 1))/length(rownames(dat_M1t))
   
     hetr2 = rbind(hetr2,p)
  
    }
 dim(dat_M1t)
   idh2 = which(hetr2[,1] > 0.2)
  if(length(idh2) == 0){
  dat_M1t = dat_M1t}else{
     dat_M1t = dat_M1t[,  -idh2]
  }
 

  dim(dat_M1t)
######################################
# Estimate the relationship matrix 
######################################
# Marker 1
dim(datMt)
missing_av = apply(X = datMt, MARGIN = 2, FUN = mean, na.rm= T) # impute the data based on the average value 
for(i in 1:ncol(datMt)){
  datMt[is.na(datMt[,i]), i] <- missing_av[i]
}
datMt[1:10,1:10]

KM1 = kinship(M = datMt, type = "add") # Kinship with the additive model 
head(KM1[1:10,1:10])

# Marker 2
missing_av1 = apply(X = dat_M1t, MARGIN = 2, FUN = mean, na.rm = T) # impute the data based on the average value 
for(i in 1:ncol(dat_M1t)){
  dat_M1t[is.na(dat_M1t[,i]), i] <- missing_av1[i]
}
dat_M1t[1:10,1:10]

KM2 = kinship(M = dat_M1t, type = "add") # Kinship with the additive model 
head(KM2[1:10,1:10])


# Combine the two relationship matrices. 
library(CovCombR)
mat_list = list(KM1,KM2)
combGmat = CovComb(Klist = mat_list) 
dim(combGmat)
write.csv(x = combGmat, file = "CombGmat_UCDavis_prog.csv", row.names = T)
# Selecting genotyeps with marker and phenotypic data 
idf = which(dat_F$germplasmName %in% rownames(combGmat))
dat_F = dat_F[idf, ]
all(unique(dat_F$germplasmName) %in% rownames(combGmat))
all(rownames(combGmat) %in% unique(dat_F$germplasmName))


```

```{r}
############################################
# five fold cross validation - I - 
##########################################
# The TRUE mean - estimated 
# 1. Trials with spatial 
# 2. Trial Without spatial 
# 3. Single replicated 
# Finally all combined together in the second step to estimate the TRUE mean values 
#4.The GBLUP fitted using the Final mean estimated 
# The BlUE data across trials

summary(BLUE_Means_Over_Trials_wide) # The TRUE mean values 
# The combined relationship matrix 
combGmat = read.csv("CombGmat_UCDavis_prog.csv") # read the combinde relationship matrix 
combGmat # combined relationship matrix 
head(combGmat[, 1:10])
rownames(combGmat) <- combGmat$X
combGmat = combGmat[,-1]
combGmat = as.matrix(combGmat)
##################
# Select genotypes with marker data 
idgno = which(BLUE_Means_Over_Trials_wide$germplasmName %in% rownames(combGmat)) 
BLUE_Means_Accession_withMarker = BLUE_Means_Over_Trials_wide[idgno,] # accessions with phenotype and marker data
dim(BLUE_Means_Accession_withMarker)
idmrk = which(rownames(combGmat) %in% BLUE_Means_Over_Trials_wide$germplasmName) # indviduals with marker and phenotype data 

combGmat_selected = combGmat[idmrk, idmrk] # selected relationship matrix 
dim(combGmat_selected)
all(rownames(combGmat_selected) %in% BLUE_Means_Accession_withMarker$germplasmName) # cross check 

BLUE_Means_Accession_withMarker = as.data.frame(BLUE_Means_Accession_withMarker)
BLUE_Means_Accession_withMarker$germplasmName = as.factor(BLUE_Means_Accession_withMarker$germplasmName)
is.matrix(combGmat_selected) # if this give false 
combGmat_selected = as.matrix(combGmat_selected)


Pred_Accu_two_stp = tibble() # store the accuracy
for(Trait in Traits){
    
    # Creating a folder that contain 5 subset with 100 times with a total of 500
    fold5 = caret::createMultiFolds(y = unique(BLUE_Means_Accession_withMarker$germplasmName), k = 5, times = 10)
    
    
    for(i in 1:length(fold5)){
      index = fold5[[i]] # the index of the sample for training set
      #subset the phenotypic data
      train_geno = droplevels(unique(BLUE_Means_Accession_withMarker$germplasmName)[index])
      train_geno_ind = which(BLUE_Means_Accession_withMarker$germplasmName %in% train_geno)
      train.data <- droplevels(BLUE_Means_Accession_withMarker %>%
                                 filter(row_number() %in% train_geno_ind)) # subset the training set
      dim(train.data)
      test.data <- droplevels(BLUE_Means_Accession_withMarker %>%
                                filter(!row_number() %in% train_geno_ind)) # subset the testing set
      dim(test.data)
      test.obs = test.data
      
      test.data[,Traits] = NA # change the grain yield of the training set to NA value
      
      mod_dat = rbind(train.data, test.data) # combine the the data set for analysis
      
      ######################## ###########
# Analysis based on the four models 
##########################################
    eval(parse(text = paste("ans <- mmer(",Trait,"~1,
                         random=~ vsr(germplasmName,Gu = combGmat_selected),
                         rcov=~vsr(units),
                         data= train.data)")))
     pred <-  as.data.frame(ans$U$`u:germplasmName`)
     dim(pred)
     pred$geno <- rownames(pred)
     idpr = which(pred$geno %in% test.data$germplasmName)
     test_pred = pred[idpr,]
     test_pred = test_pred[order(test_pred$geno),]
     test.obs = test.obs[order(test.obs$germplasmName),]
     r = cor(test_pred[,Trait], test.obs[,Trait], use = "p")
     Accu = cbind(Trait = Trait, Accuracy = r)
     Pred_Accu_two_stp = rbind(Pred_Accu_two_stp,Accu)
    # data.frame(test.obs$germplasmName, test_pred$geno)
    }
}

Pred_Accu_two_stp$Accuracy = as.numeric(Pred_Accu_two_stp$Accuracy)

ggplot(data = Pred_Accu_two_stp, mapping = aes(x = Trait, y = Accuracy, fill = Trait)) +
  geom_boxplot() + theme_bw() + theme(axis.text.x = element_text(angle = 90))

```

```{r}
############################################
#Estimating the GEBV with two step analysis 

BLUE_Means_Accession_withMarker # BlUE data with marker data for genomic prediction 
CombGmat = read.csv("CombGmat_UCDavis_prog.csv")
rownames(CombGmat) <- CombGmat$X
CombGmat = CombGmat[,-1]
CombGmat <- as.matrix(CombGmat)
idgen = BLUE_Means_Over_Trials_wide$germplasmName %in% rownames(CombGmat)
BLUE_Means_Accession_withMarker = droplevels(BLUE_Means_Over_Trials_wide[idgen, ])
dim(BLUE_Means_Accession_withMarker)

GEBV_two_step = tibble()

for(Trait in Traits){
    
      ######################## ###########
# Analysis based on the four models 
##########################################
    eval(parse(text = paste("ans <- mmer(",Trait,"~1,
                         random=~ vsr(germplasmName,Gu = CombGmat),
                         rcov=~vsr(units),
                         data= BLUE_Means_Accession_withMarker)")))
  
  
  #Extract the GEBV
   genoUef = as.matrix(ans$U$`u:germplasmName`[[Trait]])
   genoUef= as.data.frame(genoUef)
   genoUef$geno = rownames(genoUef)
   intercept = ans$Beta[1,3]
   genoUef$predict = genoUef$V1 + intercept
   colnames(genoUef)[1] = "effects"
   genoUef = genoUef[sort(genoUef$geno),]
   GEBV = genoUef[,c(2,1,3)]
   colnames(GEBV) <- c("germplasmName", "BLUP-effect", "GEBV_value") 
   GEBV = cbind(Trait = Trait, GEBV)
   rownames(GEBV) <- NULL
   GEBV_two_step = rbind(GEBV_two_step,GEBV)
    # data.frame(test.obs$germplasmName, test_pred$geno)
    }

GEBV_two_step$GEBV_value = as.numeric(GEBV_two_step$GEBV_value)
head(GEBV_two_step)
GEBV_two_step_wide = dcast(data = GEBV_two_step, formula = germplasmName ~ Trait, fun.aggregate = mean,
                           value.var = "GEBV_value", na.rm = T)

head(GEBV_two_step_wide)
summary(GEBV_two_step_wide)
```


```{r}
###################################
# single step genomic prediction - Cross Validation II
###################################
# The TRUE mean value estimated 
# 1. fit all the data together to estimate the TRUE mean value in a single step
# 2. GBLUP also done in single step
# The combined relationship matrix 
dat_F$studyName = as.factor(dat_F$studyName)
dat_F$germplasmName = as.factor(dat_F$germplasmName)
dat_F$replicate = as_factor(dat_F$replicate)

#Read phenotypic and genomic data

CombGmat <- read.csv("CombGmat_UCDavis_prog.csv")  # combined relationship matrix 
head(CombGmat[, 1:10])
rownames(CombGmat) <- CombGmat$X
CombGmat = CombGmat[,-1]

##################
# Select genotypes with marker data 
idgno = which(dat_F$germplasmName %in% rownames(CombGmat))
SL = dat_F[idgno,] # accessions with pheno and marker dta
dim(dat_F)
idmrk = which(rownames(CombGmat) %in% SL$germplasmName)


CombGmat1 = CombGmat[idmrk, idmrk]
dim(CombGmat1)
all(rownames(CombGmat1) %in% SL$germplasmName) # cross check 

SL = as.data.frame(SL)
SL$germplasmName = as.factor(SL$germplasmName)
CombGmat1 = as.matrix(CombGmat1)




Accuracy_ST = list()

library(foreach)
library(doParallel)
library(ggplot2)

#setup parallel backend to use many processors

cores=detectCores() # detect the number of cores in the computer 
cl <- makeCluster(cores-2) #reserve the number of cores in your computer for analysis
registerDoParallel(cl) # register the cores to be used for analysis 


 Accuracy_ST <- foreach(Trait = Traits) %dopar% {
  #remove outliers 
   library(lme4)
   library(sommer)
   library(LMMsolver) 
   library(dplyr)
   CombGmat
    
#Detect outlier 
eval(parse(text = paste("outl1 =  lmer(formula = ",Trait," ~ (1|germplasmName) + (1|studyName) + (1|replicate:studyName) + (1|germplasmName:studyName),
       data = dat_F)"))) 

  idout = which(abs(stats::rstudent(outl1)) >3)
  if(length(idout) == 0){
    SL = droplevles(dat_F)
  }else{
    SL = droplevels(dat_F[-idout,])
  }
 
  #Estimate the BlUE mean of the genotypes
  eval(parse(text = paste(
    "LMM = LMMsolve(fixed = ",Trait," ~ germplasmName, random = ~ studyName + replicate:studyName + studyName:germplasmName, data = SL)")))
  
Lmm_coef = coef(LMM) 
BLUE_mean = as.data.frame(Lmm_coef$germplasmName + Lmm_coef$`(Intercept)`) # Extract the predicted values
colnames(BLUE_mean)[1] = "Pred_mean"
BLUE_mean$germplasmName = gsub(pattern = "germplasmName_", replacement = "", x = rownames(BLUE_mean))  
head(BLUE_mean)
BLUE_mean[,2]
BLUE_mean = BLUE_mean[order(BLUE_mean[,2]),]


################################
# select genotypes with marker data for cross validation 
###############################
CombGmat = as.matrix(CombGmat)

idg1 = which(SL$germplasmName %in% rownames(CombGmat))
SL1 = SL[idg1,]

mrk1 = which(rownames(CombGmat) %in% SL1$germplasmName)
CombGmat1 = CombGmat[mrk1,mrk1]

# Creating a folder that contain 5 subset with 100 times with a total of 500
  fold5 = caret::createMultiFolds(y = unique(SL1$germplasmName), k = 5, times = 3)
    
    
    for(i in 1:length(fold5)){
      index = fold5[[i]] # the index of the sample for training set
      #subset the phenotypic data
      train_geno = droplevels(unique(SL1$germplasmName)[index])
      train_geno_ind = which(SL1$germplasmName %in% train_geno)
      train.data <- droplevels(SL1 %>%
                                 filter(row_number() %in% train_geno_ind)) # subset the training set
      dim(train.data)
      idNa = which(!is.na(train.data[,Trait]))
      train.data1 =  train.data[idNa,]
   
      test.data <- droplevels(SL1 %>%
                                filter(!row_number() %in% train_geno_ind)) # subset the testing set
      dim(test.data)
      test.obs = test.data
      
      test.data[,Traits] = NA # change the grain yield of the training set to NA value
      
      mod_dat = rbind(train.data, test.data) # combine the the data set for analysis
      mod_dat$germplasmName
     
     eval(parse(text = paste("ans <- mmer(",Trait,"~ 1,
                                 random=~ studyName + replicate:studyName + studyName:germplasmName + 
                                 vsr(germplasmName,Gu = CombGmat1),
                                 rcov=~vsr(units),
                                 data= train.data)")))

   #estimation of effects
   genoUef = as.matrix(ans$U$`u:germplasmName`[[Trait]])
   genoUef= as.data.frame(genoUef)
   genoUef$geno = rownames(genoUef)
   intercept = ans$Beta[1,3]
   genoUef$predict = genoUef$V1 + intercept
   colnames(genoUef)[1] = "effects"
   genoUef = genoUef[sort(genoUef$geno),]
   pred_test = as.data.frame(genoUef[genoUef$geno %in% unique(test.data$germplasmName), ])
   
   pred_test = pred_test[order(pred_test$geno), ]
   dim(pred_test)
   obs_mean = BLUE_mean[which(BLUE_mean$germplasmName %in% unique(test.data$germplasmName)),]
   obs_mean = obs_mean[order(obs_mean$germplasmName),]
   pred_test1 = pred_test[pred_test$geno %in% obs_mean$germplasmName,]
   pred_test1 = pred_test1[order(pred_test1$geno),]
   dim(pred_test1)
   
   r = cor(pred_test1[,"predict"], obs_mean[,"Pred_mean"], use = "p")
   Acc = cbind(Trait = Trait, Accuracy = r) 
      
    Accuracy_ST = rbind(Accuracy_ST, Acc) 
  
    }
  Accuracy_ST
}

stopCluster(cl) # Stop the cluster 

##Organize the output data from list to data frame
Accuracy_ST_Comb = tibble()
for(i in 1:length(Accuracy_ST)){
  ac1 = Accuracy_ST[[i]]
  ac2 = as.data.frame(ac1)
  for(j in 1:50){
  ac21 = as.data.frame(ac2[j,])
  accf = cbind(Trait = ac21[[1]][[1]], Accuracy = ac21[[2]][[1]])
 Accuracy_ST_Comb=  rbind(Accuracy_ST_Comb, accf) 
  }
}

Accuracy_ST_Comb$Accuracy = as.numeric(Accuracy_ST_Comb$Accuracy)

ggplot(data = Accuracy_ST_Comb, mapping = aes(x = Trait, y = Accuracy, fill = Trait)) +
  geom_boxplot() + theme_bw() + theme(axis.text.x = element_text(angle = 90))
```

```{r}
###########################################
# GEBV - for single step
CombGmat = read.csv("CombGmat_UCDavis_prog.csv")
rownames(CombGmat) <- CombGmat$X
CombGmat = CombGmat[,-1]
CombGmat = as.matrix(CombGmat)

###############################
# Estimating GEBV
GEBV_singlestep = tibble()

#Estimating the BLUE 
for(Trait in Traits){
eval(parse(text = paste("outl1 =  lmer(formula = ",Trait," ~ (1|germplasmName) + (1|studyName) + (1|replicate:studyName) + (1|germplasmName:studyName),
       data = dat_F)"))) 

  idout = which(abs(stats::rstudent(outl1)) >3)
  if(length(idout) == 0){
    SL = droplevles(dat_F)
  }else{
    SL = droplevels(dat_F[-idout,])
  }

# Selecting genotypes with marker and phenotype data   
idg1 = which(SL$germplasmName %in% rownames(CombGmat))
SL1 = droplevels(SL[idg1,])
mrk1 = which(rownames(CombGmat) %in% SL$germplasmName)
CombGmat1 = CombGmat[mrk1,mrk1]
dim(CombGmat1)


     eval(parse(text = paste("ans <- mmer(",Trait,"~ 1,
                                 random=~ studyName + replicate:studyName + studyName:germplasmName + 
                                 vsr(germplasmName,Gu = CombGmat1),
                                 rcov=~vsr(units),
                                 data= SL1)")))

   genoUef = as.matrix(ans$U$`u:germplasmName`[[Trait]])
   genoUef= as.data.frame(genoUef)
   genoUef$geno = rownames(genoUef)
   intercept = ans$Beta[1,3]
   genoUef$predict = genoUef$V1 + intercept
   colnames(genoUef)[1] = "effects"
   genoUef = genoUef[sort(genoUef$geno),]
   GEBV = genoUef[,c(2,1,3)]
   colnames(GEBV) <- c("germplasmName", "BLUP-effect", "GEBV_value") 
   GEBV = cbind(Trait = Trait, GEBV)
   rownames(GEBV) <- NULL
   
   GEBV_singlestep = rbind(GEBV_singlestep,GEBV )
}

head(GEBV_singlestep)
str(GEBV_singlestep)

GEBV_singlestep_wide = dcast(data = GEBV_singlestep, formula = germplasmName ~ Trait, fun.aggregate = mean, value.var = "GEBV_value", na.rm = T)
head(GEBV_singlestep_wide)
dim(GEBV_singlestep_wide)
summary(GEBV_singlestep_wide)
summary(GEBV_two_step_wide)
#############################
# Saving the GEBV values for the single and two step analysis
library(openxlsx)

out_GEBV = list(GEBV_Two_step = GEBV_two_step_wide, GEBV_Single_step = GEBV_singlestep_wide)
write.xlsx(x = out_GEBV, file = "GEBV_Estimate_for_UCDavis_Nov_2023.xlsx", rowNames = F)





```
